apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: 
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: 
resources:
  - manifests.yaml