apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: 4ab74bff204a0fcf5c8ce3a4fe523e40d8b1d7d5
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: 4ab74bff204a0fcf5c8ce3a4fe523e40d8b1d7d5
resources:
  - manifests.yaml