apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-front
    newTag: 783e2417b54f0418d1bc30a754f94cbfc744837f
  - name: gitopsflowacr.azurecr.io/azvote/azure-vote-back
    newTag: 783e2417b54f0418d1bc30a754f94cbfc744837f
resources:
  - manifests.yaml