apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:  
  - name: gitopsflowacr.azurecr.io/azvote/azvote/azure-vote-back
    newTag: 813c26e47282304447c2365c7c300b737d723c5a

resources:
  - manifests.yaml