apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: gitopsflowacr.azurecr.io/azvote/azvote/azure-vote-front
    newTag: 9ab4d9e39d346262022317c65a43b2be34523414
    
resources:
  - manifests.yaml