apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: az-vote-app
  namespace: flux-system
spec:
  dependsOn:
    - name: fake-resource
  interval: 30s
  path: ./kustomize-azure-vote-app-deployment/overlays/staging
  prune: true
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: azure-vote-front
      namespace: az-vote-stage
    - apiVersion: v1
      kind: Service
      name: azure-vote-back
      namespace: az-vote-stage  
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client