
# resources:
#   containers:
#   - container: chart-testing
#     image: quay.io/helmpack/chart-testing:v3.3.0

trigger: none
pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

container: quay.io/helmpack/chart-testing:v3.3.0
options: sh  

steps:
 - task: Bash@3
   inputs:
     targetType: 'inline'
     script: 'ct lint --all --debug --chart-dirs .'
