imageName: kaizentm/gitops-connector
imageTag: 0.1.44
containerPort: 8080

gitRepositoryType: 
ciCdOrchestratorType: 
gitOpsOperatorType: 
gitOpsAppURL: https://github.com/kaizentm/gitops-manifests/commit
azdoGitOpsRepoName: test
azdoPrRepoName: 
azdoOrgUrl: 
orchestratorPAT: 

gitHubGitOpsRepoName: 
gitHubGitOpsManifestsRepoName: 
gitHubOrgUrl: 